# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LectureClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SavedTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('selection_level', models.CharField(choices=[('M', 'Mandatory'), ('S', 'Mandatory_Selectable'), ('E', 'Extra')], max_length=25)),
                ('hours', models.IntegerField()),
                ('population_estimate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('M', 'Monday'), ('Tu', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thurday'), ('F', 'Friday')], max_length=2)),
                ('hour', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lectureclass',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_main.Subject'),
        ),
        migrations.AddField(
            model_name='lectureclass',
            name='save_it_belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_main.SavedTable'),
        ),
        migrations.AddField(
            model_name='lectureclass',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_main.Timeslot'),
        ),
    ]
