# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=10)),
                ('room_size', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='lectureclass',
            old_name='lecture',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='lectureclass',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ta_main.Room'),
        ),
    ]
