# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_main', '0002_auto_20171028_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='title_asp',
            field=models.CharField(default='asp_autofill', max_length=50),
            preserve_default=False,
        ),
    ]
