# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_main', '0005_courseyear_lecturer_subjectscourses_teaches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseyear',
            name='mandatory_count',
        ),
        migrations.RemoveField(
            model_name='courseyear',
            name='selective_count',
        ),
    ]
