# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta_main', '0006_auto_20171111_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject1', to='ta_main.Subject')),
                ('subject2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject2', to='ta_main.Subject')),
            ],
        ),
    ]
