# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_main', '0007_clash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clash',
            old_name='subject',
            new_name='subject1',
        ),
    ]
