# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta_main', '0007_clash'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_string', models.CharField(max_length=20)),
                ('day_asp', models.IntegerField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_main.SavedTable')),
            ],
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_main.DayDef'),
        ),
    ]
