# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta_main', '0008_auto_20171128_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSizeDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='daydef',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_main.TableSizeDef'),
        ),
    ]
