# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta_main', '0010_savedtable_table_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtable',
            name='table_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_main.TableSizeDef'),
        ),
    ]
