# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_main', '0008_auto_20171122_1658'),
        ('ta_main', '0011_auto_20171129_0108'),
    ]

    operations = [
    ]
