# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_main', '0012_merge_20171129_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesizedef',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
