# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_main', '0013_auto_20180106_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotblocker',
            name='title',
            field=models.CharField(default='Blocks something', max_length=80),
        ),
    ]
